# Generated by Django 6.0.3 on 2026-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bento Candles', 'Bento Candles'), ('Scented Candles', 'Scented Candles'), ('Decorative Candles', 'Decorative Candles'), ('Gift Collections', 'Gift Collections'), ('Ceremony Candles', 'Ceremony Candles'), ('Bougies de cérémonie', 'Ceremony Candles'), ('Plaster Sachets', 'Plaster Sachets')], default='Scented Candles', max_length=120),
        ),
    ]
